### ISSUE TITLE
TravisCI build failing

### ISSUE THREAD

**Issue by leios** [algorithm-archivists/algorithm-archive#620] opened 2019-07-10 21:51 UTC
# Bug Report

The TravisCI build is failing after the most recent PR merge #858

## Description

Here is the error on TravisCI: https://travis-ci.org/algorithm-archivists/algorithm-archive

It is breaking here at 

```
Error: version not found: gitbook-plugin-api-language-selector@1.0.3
```

## Additional context
Note, `gitbook install` seems to work on my local machine.

## For Algorithm Archive Developers

- [x] The bug can be reproduced
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by dovisutu** [comment] 2019-07-11 07:41
It seems that this error isn't cause by merging of #614 , because the error occurs in one earlier [CI #857](https://travis-ci.org/algorithm-archivists/algorithm-archive/builds/556835344) for PR #595 when I locally squash commit.
but build #856 and earlier didn't crash. Something must happen during that period...

**Comment by leios** [comment] 2019-07-11 07:58
Great, thanks for the additional information! I'll be looking into this more soon.

**Comment by leios** [comment] 2019-07-11 11:26
This is fixed, but I am leaving the issue open because I don't understand the solution.

Ultimately, we updated [this](https://github.com/algorithm-archivists/gitbook-plugin-api-language-selector/blob/89bd5850c1c189c022895f31832bbc69b5c35ab3/package.json#L47) to be version 3.0.0 and then cleared the cache.

I am honestly not sure if we should have done this or if it even helped. Everything was failing before this was changed and everything is working now.

**Comment by berquist** [comment] 2019-09-09 02:13
Broken again:
```
info: loading plugin "mathjax"... ERROR

PluginError: Error with plugin "mathjax": Cannot find module 'mathjax/unpacked/MathJax'
```
Here is the difference between a build that worked:
```
info: installing plugin "mathjax" 
info: install plugin "mathjax" (https://github.com/algorithm-archivists/plugin-mathjax) from NPM with version https://github.com/algorithm-archivists/plugin-mathjax 
/home/travis/build/algorithm-archivists/algorithm-archive
├── gitbook-plugin-api-language-selector@3.0.0  (git+https://github.com/algorithm-archivists/gitbook-plugin-api-language-selector.git#89bd5850c1c189c022895f31832bbc69b5c35ab3)
├── gitbook-plugin-bibtex-cite@1.1.0 
├── gitbook-plugin-bulk-redirect@0.2.1 
├── gitbook-plugin-fontsettings@2.0.0 
├── gitbook-plugin-ga@1.0.1 
├── gitbook-plugin-include-codeblock@3.2.2 
├── gitbook-plugin-mathjax@1.1.2  (git+https://github.com/algorithm-archivists/plugin-mathjax.git#08ef2363fce2ddcec55571ff563b96d07cb2e9d6)
├── gitbook-plugin-prism@2.4.0 
└── gitbook-plugin-wordcount@0.0.1 

info:  plugin "mathjax" installed with success 
```
And the currently failing ones that don't:
```
info: installing plugin "mathjax" 
info: install plugin "mathjax" (https://github.com/algorithm-archivists/plugin-mathjax) from NPM with version https://github.com/algorithm-archivists/plugin-mathjax 
/home/travis/build/algorithm-archivists/algorithm-archive
├── gitbook-plugin-api-language-selector@3.0.0 (git+https://github.com/algorithm-archivists/gitbook-plugin-api-language-selector.git#9a11f795e607f00e556de26d2f476f1a8cb20a5b)
├── gitbook-plugin-bibtex-cite@1.1.0
├── gitbook-plugin-bulk-redirect@0.2.1
├── gitbook-plugin-fontsettings@2.0.0
├── gitbook-plugin-ga@1.0.1
├── gitbook-plugin-include-codeblock@3.2.2
├─┬ gitbook-plugin-mathjax@1.1.2 (git+https://github.com/algorithm-archivists/plugin-mathjax.git#08ef2363fce2ddcec55571ff563b96d07cb2e9d6)
│ └─┬ mathjax-node@0.5.2
│   └─┬ mathjax@3.0.0
│     └── mathjax-full@3.0.0 (git://github.com/mathjax/MathJax-src.git#f73c0c7012370271aa9cdab06259fcceebb0d703)
├── gitbook-plugin-prism@2.4.0
└── gitbook-plugin-wordcount@0.0.1

info:  plugin "mathjax" installed with success 
```
Somehow there are new dependencies of the MathJax plugin despite the plugin not being updated?

**Comment by berquist** [comment] 2019-09-09 02:19
Deleting the caches didn't help this time. It looks like the `package-lock.json` from the plugin is being ignored? https://github.com/algorithm-archivists/plugin-mathjax/blob/08ef2363fce2ddcec55571ff563b96d07cb2e9d6/package-lock.json#L388 See 2.7.5 being specified, but the failing build pulling in 3.0.0.

**Comment by leios** [comment] 2019-09-09 09:44
I've confirmed that this error appears at all old PR's. I am also unable to build the book locally -- even on a clean clone using the upstream mathjax plugin.

I also don't know where to specify the mathjax version, except in the `book.json` file, which seems to be completely ignored upon `gitbook install`, which is why I tried to build everything on a clean repo without our version of the mathjax plugin.

**Comment by segfaulted** [comment] 2019-09-09 11:05
The mathjax plugin requires a npm package `mathjax-node` which then requires the package `mathjax`. The issue is `mathjax-node` requires any version of `mathjax` which defaults to the newest version which is version 3.0.0 released 5 days ago. The version of `mathjax-node` the plugin was built for the version 2.* branch. 

You can `npm install mathjax@^2.7.0`  after `gitbook install` and serve should work. You might need to delete the node_modules folder or use a clean clone to get back to clean state before running those commands.

I also just submitted a pull request(https://github.com/algorithm-archivists/plugin-mathjax/pull/2) to your fork of the mathjax plugin that adds a dependency on the on the 2.7 branch of the mathjax which should fix the dependency issue. You might need to clear your node_modules folder for it to download the correct versions on your local copy.

**Comment by leios** [comment] 2019-09-09 11:32
After merging @segfaulted's PR, everything builds for now. Thanks!

What do we need to do to upgrade to the latest version? Should we just keep the current version since we are trying to make new gitbook-like software for the algorithm archive?

**Comment by segfaulted** [comment] 2019-09-09 11:52
I didn't dig too deep when I was looking into the problem but believe the dependency fix would work on the upstream plugin also, I don't know if there are any other issues you have with upstream. I actually just discovered this project from your stream on twitch where you were ran into this issue.

**Comment by leios** [comment] 2019-09-09 11:53
Well, I'm glad you were there! Are you on discord? https://discord.gg/Pr2E9S6

**Comment by ntindle** [comment] 2021-08-28 05:23
@leios can we close this?

**Comment by Amaras** [comment] 2021-08-28 09:47
Travis is no longer used. I'm closing it now, since it's not relevant any more.

**Closed by Amaras** 2021-08-28 09:47 UTC
Labels: Problem
