### ISSUE TITLE
Pseudo-code

### ISSUE THREAD

**Issue by gammison** [algorithm-archivists/algorithm-archive#207] opened 2018-07-02 21:32 UTC
Since this is primarily a book, would it make since to provide pseudo code for each of the algorithms, something like CLRS's style. I think this would make implementing algorithms, and checking for errors in submitting implementations, a bit easier. It may also be useful if we ever intend to add complexity proofs to the chapters.

**Comment by julianschacher** [comment] 2018-07-02 21:33
We decided at some point to not use `pseudo-code` and just use `julia` as the standard language.

**Comment by julianschacher** [comment] 2018-07-02 21:34
That's the current state. Maybe @leios has some other/new comments/opinions on that.

**Comment by leios** [comment] 2018-07-02 22:16
Hey @gammison, about pseudo-code... when I was originally writing this book, I was using pseudo-code. The problem is that there isn't really a good, consistent style for pseudo-code. In addition, pseudo-code will often obscure important implementation details that you need to see actual code to understand. Since the point of this book is to help people code up these algorithms, pseudo-code was a bit of a cop-out.

That said, I am interested to hear how pseudo-code would help with the AAA in more explicit terms. Could you provide some examples of how this?

**Comment by gammison** [comment] 2018-07-02 23:18
Yeah so I had two thoughts. One, with a pseudo-code reference, it would be easier to get a big picture of the algorithm without getting bogged down in a particular languages implementation. It would obscure some of the details but I don't necessarily think that's a bad thing since real implementations would be as well. One example may be implementing one of the sub O(n^2) matrix multiplication algorithms since you could put matrix notation in the pseudo code. I agree that there's no consistent style, just like there's not a consistent style of proof in mathematics.

Secondly, pseudo code is almost always used to prove correctness and complexity of algorithms. I don't know if you want the book to eventually include more CS Theory but if you do, I think pseudo code is a necessity (there are also algorithms that lay mostly in cs theory, like how to do reductions or transform Turing machines). Taking quick sort as an example,  you would want to write pseudo code for it, prove it's correct, then prove it's time or space complexity (For quick sort, this involves constructing random input, then showing that the expected runtime is O(nlogn)).

**Comment by leios** [comment] 2018-07-02 23:48
@gammison I see what you mean. The main criticisms I have of pseudo-code is how far removed it is from actual implementation details and how there is no standard pseudo-code format; however, I don't mind adding it in. Outside of CLRS, do you have other pseudo-code examples we could look at to try to create an Algorithm Archive standard from?

**Comment by gammison** [comment] 2018-07-03 00:28
Beyond CLRS, there are some latex packages that enforce some standards, mostly indentation and line numbering, and some return info. There's info for that [here](https://en.wikibooks.org/wiki/LaTeX/Algorithms). You might also want to look at the analysis of algorithm course slides that I had during a course I took, you can find them [here](http://csorw4231-14.wikischolars.columbia.edu)

Adding it as a language may be an option, but I think it should be more separate, part of the article rather than code examples, don't really know.

**Comment by leios** [comment] 2018-07-03 00:44
@gammison If it's added, it will most likely be added as a separate language. The language implementations are already written as part of the bulk text of the book, and I really like this feature. Having pseudocode in the text and then code snippets at the end devalues the code, itself, which is often more readable and clear than pseudo-code. 

As a note, I am not sure how well the LaTeX snippets will play with gitbook, but we can give it a shot.

**Comment by Butt4cak3** [comment] 2018-07-03 10:22
Two put in my two cents: I think we had valid reasons to get rid of pseudo code. I also don't think it would add anything that you can't get from reading one or two actual implementations. The rest is explained in the chapters.

**Comment by Butt4cak3** [comment] 2018-07-16 07:49
I'll go ahead and close this for now. This thread is pretty much dead and I don't think it's going to happen anyway.

**Closed by Butt4cak3** 2018-07-16 07:49 UTC
Labels: Discussion
